language: node_js
node_js:
  - "stable"

sudo: required

services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME"/spotify-graphql .
  

install:
  npm install && npm run test

script:
  - docker images $DOCKER_USERNAME"/spotify-graphql

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push bluecitylights/spotify-graphql;
    fi
  
